### PR TITLE
Review fixes

### LINKED ISSUE #12: Provider Review
Hello! 

My name is Clint, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I believe the issues are all fairly minor and can likely be cleaned up pretty quickly. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit c950dddafb1baa9b3926de1986809c6238562bbb .

- [x] ~resource_floating_ip: `prefix_length` is documented to only accept a value of `56`, and if I read correctly, only when `ip_version` is `6`. If this is the case then consider adding validation functions to their schema definitions. For `ip_version`, validate it is either `4` or `6`. For `prefix_length` unfortunately we can’t validate it is `56` only when `ip_version` is `6`, but you can validate it’s value~ discussed 👍 
- [ ] I believe the markdown documentation files need to have extention `.html.markdown` (or `.html.md`), otherwise the conversion will not have the `.html` extension. Terraform.io is a static html site so that will be required. 
- [x] when deleting a resource, please check the error code. If your API returns a `404` error if the resource is not found (or already deleted) then we need to capture that error, log that the resource could not be found, and call `d.SetId(“”)`. The Server resource does this. See also Route53 Record example: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_route53_record.go#L637-L650
- [x] ~resource_server: `volume_size_gb` is said to default to `10`. We should include that default in the schema definition. Right now it’s defined as `Optional` and `ForceNew` . If not a default locally, should it be `Computed` as well? I would need to test it out and view tests to confirm~ discussed 👍 
- [x] resource_server: `ssh_keys` are not read from the API. Are they available? Can you describe the expected behavior of this attribute? 
- [x] resource_server: attributes that are `TypeList`: Lists are generally ordered. If the API does not return them in the same order they are provided, there can be conflict. Consider `TypeSet` for attributes were there could be more than 1 stanza block of it, and ordering is not relevant. If ordered is relevant, we need to ensure Terraform is enforcing the ordering from the configuration.
- [x] resource_server: line 294, 322, 325, 327, etc: when calling `d.Set` for anything that is not a scalar value, it’s important to check the error returned. If the value is not in the correct format, you’ll ignore the error, and the state will match the configuration and not the returned value from the API, which can lead to undetected drift. Here’s an example: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_db_instance.go#L825-L831

In summary, things look really good. I have not had a chance to evaluate the tests because I don’t yet have credentials to a test account. I believe someone at HashiCorp will be reaching out to get those.

Let me know if you have any questions! 

Cheers,
Clint

--------

Update from October 18, 2017: 

- Considering all above items addressed when #13 is merged

### PR DESCRIPTION
**Pull request by thetonymaster**
closes #12

### CODE REVIEW

File: cloudscale/resource_cloudscale_server.go [hunk 1]
```diff
@@ -56,6 +56,7 @@ func getServerSchema() map[string]*schema.Schema {
 			Type:     schema.TypeInt,
 			Optional: true,
 			ForceNew: true,
+			Default:  10,
```
Comment (davidhalter) [inline cloudscale/resource_cloudscale_server.go]: I'm not sure if this necessary anymore, since we kind of discussed this?

Comment (thetonymaster) [reply cloudscale/resource_cloudscale_server.go]: Agree, was just playing around with terraform, and checking if it actually broke something. I will remove it.

**Comment by davidhalter** [comment]
Everything else seems good IMO! Thanks for making the changes. Now I'm just waiting for @catsby to say that this is indeed what we want.

Thanks Antonio!

File: cloudscale/resource_cloudscale_floating_ip.go [hunk 2]
```diff
@@ -136,13 +137,22 @@ func resourceFloatingIPUpdate(d *schema.ResourceData, meta interface{}) error {
...
-
 	id := d.Id()
 
+	log.Printf("[INFO] Deleting FloatingIP: %s", d.Id())
 	err := client.FloatingIPs.Delete(context.Background(), id)
+
+	if err != nil && strings.Contains(err.Error(), "Not found") {
+		log.Printf("[WARN] FloatingIP (%s) not found", d.Id())
+		d.SetId("")
+		return fmt.Errorf("Error deleting FloatingIP: %s", err)
```
Comment (catsby) [inline cloudscale/resource_cloudscale_floating_ip.go]: I believe in this scenario "I tried to delete this IP, but it was not found" then you should return `nil` and not an error. We came here to destroy it, but it was already destroyed, so we log that it in fact wasn't found, but otherwise we've accomplished what we wanted to here.

If we do return error here, Terraform will error out and stop in the middle of an `apply`, where in this scenario we should just keep going; the resource is gone. 

As is, a user would have to re-plan and re-apply to continue, but there would be no real change because here we've already removed the IP from state on line 147. 

So, just return `nil` here 😄

Comment (catsby) [reply cloudscale/resource_cloudscale_floating_ip.go]: AWS Route53 Record example:

- https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_route53_record.go#L637-L650

AWS VPC example:

- https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpc.go#L465-L493

**Review by catsby — APPROVED** [review]
One simple `return` change requested, feel free to merge after that without re-review from me 👍
